### PR TITLE
feat: folder_and_file variable

### PR DESCRIPTION
**Pull request by localip**
This allows for the following styles of RPC:

RPC when there's no workspace:
image

RPC when there is a workspace, but the file is in the root of said workspace:
image

RPC when there is a workspace and a parent folder to the file being edited:
image

This is mainly to give the RPC more context as "index.ts" in a workspace doesn't describe much to someone viewing the RPC.

### CODE REVIEW

**Comment by localip** [comment]
@leonardssh

**Comment by localip** [comment]
@leonardssh Bump.

**Comment by leonardssh** [comment]
Thanks for your contribution @localip.

This PR will be part of #83.

**Comment by xhayper** [comment]
yeah we might need someone to resolve the conflicts

**Comment by localip** [comment]
@xhayper Good to go!

**Comment by xhayper** [comment]
amazing work! i will work on it tomorrow! i need to sleep

**Pull request merged**
