### PR TITLE
Multiple buttons

### PR DESCRIPTION
**Pull request by nick22985**
Multiple button support for presence

Closes: #144

### CODE REVIEW

**Comment by nick22985** [comment]
Closes: #144 when done

**Comment by nick22985** [comment]
I don't see a reason to add support for each individual status for this. If in the future it comes us we can but cant see it be useful

**Comment by xhayper** [comment]
this is getting more messy the more feature we add, we should have a common function that check for stuff

**Comment by nick22985** [comment]
Made the buttons into a separate function. The other stuff by the looks of it realise on everything else

**Pull request merged**
