### PR TITLE
Added language: reStructuredText

### PR DESCRIPTION
**Pull request by Eutropios**
Added icon for reStructuredText, a documentation language.

Signed off: Eutropios

### CODE REVIEW

**Comment by Eutropios** [comment]
I wasn't sure if this was too little or not. The language's logo is very barren, so I just use the initials of the language. I created this via Inkscape. The software's (docutils) license is OSI-Approved Open Source, Public Domain, so we should be fine using a modified version of it.

Image: reStructuredText logo.
Source: (reStructuredText Logo - Wikimedia)<https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/ReStructuredText_Logo.svg/517px-ReStructuredText_Logo.svg.png>

**Comment by xhayper** [comment]
the logo looks great! but can you add a background color please? thank you!

**Comment by Eutropios** [comment]
> the logo looks great! but can you add a background color please? thank you!

Sure! What colour do you think would be a good fit for this?

**Comment by xhayper** [comment]
maybe dark blue? hmm...

**Comment by leonardssh** [comment]
Dark blue: #4379ac @Eutropios 

image

**Comment by Eutropios** [comment]
Sounds good!

**Comment by Eutropios** [comment]
Sounds good!

**Comment by Eutropios** [comment]
First commit was a naming mistake which the second corrects

**Pull request merged**
