### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by tr1xem**
To fix rpc not loading on reload . restart and various events  a quick fix that works

### CODE REVIEW

**Comment by leonardssh** [comment]
Let's try and see if it works.

**Review by leonardssh — APPROVED** [review]

**Comment by Naveandice** [comment]
Unfortunately, not for me. It loads faster than vscode.git and gives an error. Should I open an issue for this?

**Comment by leonardssh** [comment]
@Naveandice I've changed it back to `onStartupFinished`.

**Comment by Naveandice** [comment]
It's fixed now, thanks!

**Pull request merged**
