### PR TITLE
feat: add support for file_size tag

### LINKED ISSUE #70: Add `${file_size}`
Add `${file_size}` in RPC: Details* (Settings) please, which will be replaced with size of file

### PR DESCRIPTION
**Pull request by espenja**
Closes #70 

Adds support for `{file_size}` as a tag.
Uses [https://www.npmjs.com/package/file-size](https://www.npmjs.com/package/file-size) (0 dependencies) for human readable formatting.
Human readable formatting can be enabled by setting the config value `rpc.fileSizeHumanReadable` to `true`.
If `rpc.fileSizeHumanReadable` is set to `false`, `B` will be used to represent `bytes` instead, and the file size will be formatted with `toLocaleString`.

Example display:
image
With configuration:
```json
{
  "rpc.fileSizeHumanReadable": true,
  "rpc.fileSizeSpec": "iec",
  "rpc.fileSizeFixed": 2,
  "rpc.detailsEditing": "In {workspace} {file_extension} {file_size}",
}
```

Default values for configuration is the default values for the dependency `file-size`.

### CODE REVIEW

**Comment by xhayper** [comment]
PR looks amazing, will test it it tomorrow

**Comment by xhayper** [comment]
could you resolve the merge conflict?

**Comment by espenja** [comment]
@xhayper Should be resolved now

**Comment by xhayper** [comment]
Amazing work! Thank you!

**Pull request merged**
