### PR TITLE
Add "add seconds to the elapsed timestamp"

### PR DESCRIPTION
**Pull request by michioxd**
It should be look like this

Discord_Zzsp3pxpe8

I set my value to 9000 seconds (= 2.5 hours = 02:30:00). Default is 0

### CODE REVIEW

**Comment by leonardssh** [comment]
Thanks for your contribution, may I know what is the purpose of this feature? Why would you want it to start at a certain time?

**Comment by michioxd** [comment]
> Thanks for your contribution, may I know what is the purpose of this feature? Why would you want it to start at a certain time?

Because i lost timestamp (it reset to 0) after i add a folder to my workspace... So now i made it :v

**Comment by michioxd** [comment]
I found an issue, after i changed file or line, it subtracted timestamp, so i fixed with [e5008ea](https://github.com/leonardssh/vscord/pull/218/commits/e5008ea45543c3ac5a83191493b8a6ff1a402705)

**Review by leonardssh — APPROVED** [review]
LGTM!

**Comment by xhayper** [comment]
I am unsure if we should merge this because it is very specific

**Pull request closed without merging**
