### PR TITLE
feat: Refactoring Buttons

### PR DESCRIPTION
**Pull request by nick22985**
#165 
#158 
#176 

- [x] Buttons refactored and changes / tested
- [x] Add validation for labels and url and that in the buttons itself discord doesnt allow these to be an empty string if. Will crash if it is
- [x] Reconfigure how the button config works use objects instead
- [x] Update descriptions to make it more readable. Change the names of config options if needed
- [x] ~~Add deperacted to the old settings. Explain were to put the new options~~ Invalid

### CODE REVIEW

**Comment by nick22985** [comment]
**Full Config for buttons in JSON settings**
```
"vscord.status.buttons": {
	"button1": {
		"enabled": true,
		"active": {
			"label": "Check Out My Github",
			"url": "https://github.com/nick22985",
			"enabled": true
		},
		"idle": {
			"label": "Check Out My Github",
			"url": "https://github.com/nick22985",
			"enabled": true
		},
		"inactive": {
			"label": "Check Out My Github",
			"url": "https://github.com/nick22985",
			"enabled": true
		},
		"git": {
			"idle": {
				"label": " View Repository ",
				"url": "{git_url}",
				"enabled": true
			},
			"active": {
				"label": "View Repository",
				"url": "{git_url}",
				"enabled": true
			},
			"inactive": {
				"label": "View Repository",
				"url": "{git_url}",
				"enabled": true
			}
		}
	},
	"button2": {
		"enabled": true,
		"active": {
			"label": "Check Out My Website",
			"url": "https://nick22985.com",
			"enabled": true
		},
		"idle": {
			"label": "Check Out My Website",
			"url": "https://nick22985.com",
			"enabled": true
		},
		"inactive": {
			"label": "Check Out My Website",
			"url": "https://nick22985.com",
			"enabled": true
		},
		"git": {
			"idle": {
				"label": "Check Out My Github",
				"url": "https://github.com/nick22985",
				"enabled": true
			},
			"active": {
				"label": "Check Out My Github",
				"url": "https://github.com/nick22985",
				"enabled": true
			},
			"inactive": {
				"label": "Check Out My Github",
				"url": "https://github.com/nick22985",
				"enabled": true
			}
		}
	}
},
```

**Comment by leonardssh** [comment]
🤩

**Review by nick22985 — COMMENTED** [review]
Tested! Let me know any feedback

The old config still works no need to add deprecated settings. If people want to switch they can. Think this is def the better expirences for the user

**Review by leonardssh — APPROVED** [review]

**Review by xhayper — APPROVED** [review]

**Comment by atakiya** [comment]
For anyone else stumbling over this PR and wondering why the supposedly new configuration does not work: 817fa07b2af07d3d49cb0989727268192f69e686 was a revert

**Pull request merged**
