### PR TITLE
Add Reason icon

### PR DESCRIPTION
**Pull request by aleksrutins**
The image isn't quite the same as the official icon, but it's close enough to hopefully be recognizable.

### CODE REVIEW

**Comment by localip** [comment]
Any reason why you didn't use https://avatars.githubusercontent.com/u/20414525?s=280&v=4?

**Comment by aleksrutins** [comment]
Hmm, it still doesn't work.

**Comment by xhayper** [comment]
weird

**Comment by aleksrutins** [comment]
image

**Comment by xhayper** [comment]
Very weird, give me a moment.

**Comment by xhayper** [comment]
image
works for me

**Pull request merged**
